
export enum Block {
    // Background
    Default = "#4b3431",
    // Locked
    Locked = "black",
    // Blank
    Blank = "#c6ab8c",
    // Swords
    Swords = "blue",
    // Present
    Crate = "red",
    // Fox
    Fox = "purple",
}

const f = Block.Fox, s = Block.Swords, c = Block.Crate, l = Block.Locked, b = Block.Blank, d = Block.Default;

export const Boards = {
    Default: [
        [d, d, d, d, d, d],
        [d, d, d, d, d, d],
        [d, d, d, d, d, d],
        [d, d, d, d, d, d],
        [d, d, d, d, d, d],
        [d, d, d, d, d, d],
    ],
    aur1c1: [
        [c, c, b, f, f, b],
        [c, c, l, b, l, b],
        [f, l, b, b, s, s],
        [b, b, b, b, s, s],
        [b, b, l, b, s, s],
        [f, b, b, b, b, l],
    ],
    aur1c2: [
        [b, b, b, f, f, b],
        [b, b, l, b, l, b],
        [f, l, c, c, s, s],
        [b, b, c, c, s, s],
        [b, b, l, b, s, s],
        [f, b, b, b, b, l],
    ],
    aur2c1: [
        [c, c, b, b, b, b],
        [c, c, l, f, l, b],
        [b, l, b, s, s, f],
        [b, b, b, s, s, b],
        [b, b, l, s, s, b],
        [b, b, b, f, f, l],
    ],
    aur2c2: [
        [b, b, b, b, b, b],
        [b, b, l, f, l, b],
        [b, l, b, s, s, f],
        [c, c, b, s, s, b],
        [c, c, l, s, s, b],
        [b, b, b, f, f, l],
    ],
    aur3c1: [
        [c, c, b, b, b, f],
        [c, c, l, b, l, b],
        [b, l, b, f, f, b],
        [b, b, f, s, s, b],
        [b, b, l, s, s, b],
        [b, b, b, s, s, l],
    ],
    aur3c2: [
        [b, b, b, b, b, f],
        [b, b, l, b, l, b],
        [b, l, b, f, f, b],
        [c, c, f, s, s, b],
        [c, c, l, s, s, b],
        [b, b, b, s, s, l],
    ],
    aur4c1: [
        [b, b, b, f, f, b],
        [b, b, l, b, l, b],
        [f, l, b, s, s, s],
        [c, c, b, s, s, s],
        [c, c, l, b, b, b],
        [f, b, b, b, b, l],
    ],
    aur4c2: [
        [b, b, b, f, f, b],
        [b, b, l, b, l, b],
        [f, l, b, s, s, s],
        [b, b, b, s, s, s],
        [b, b, l, c, c, b],
        [f, b, b, c, c, l],
    ],
    aur5c1: [
        [c, c, b, b, b, f],
        [c, c, l, b, l, b],
        [b, l, b, f, f, b],
        [b, b, f, s, s, s],
        [b, b, l, s, s, s],
        [b, b, b, b, b, l],
    ],
    aur5c2: [
        [b, b, b, b, b, f],
        [b, b, l, b, l, b],
        [b, l, b, f, f, b],
        [b, b, f, s, s, s],
        [c, c, l, s, s, s],
        [c, c, b, b, b, l],
    ],
    aur6c1: [
        [c, c, f, b, b, b],
        [c, c, l, b, l, f],
        [b, l, s, s, s, b],
        [b, b, s, s, s, b],
        [b, b, l, b, b, f],
        [b, b, f, b, b, l],
    ],
    aur6c2: [
        [b, b, f, b, b, b],
        [b, b, l, b, l, f],
        [b, l, s, s, s, b],
        [b, b, s, s, s, b],
        [c, c, l, b, b, f],
        [c, c, f, b, b, l],
    ],
    aur7c1: [
        [b, b, f, b, b, b],
        [b, b, l, b, l, f],
        [b, l, b, b, b, b],
        [s, s, b, b, b, b],
        [s, s, l, c, c, f],
        [s, s, f, c, c, l],
    ],
    aur7c2: [
        [b, b, f, b, b, b],
        [b, b, l, b, l, f],
        [b, l, b, b, c, c],
        [s, s, b, b, c, c],
        [s, s, l, b, b, f],
        [s, s, f, b, b, l],
    ],
    aur7c3: [
        [b, b, b, b, b, b],
        [b, b, l, f, l, b],
        [b, l, b, b, b, f],
        [s, s, b, b, c, c],
        [s, s, l, b, c, c],
        [s, s, b, f, f, l],
    ],
    aur7c4: [
        [b, b, b, b, b, b],
        [b, b, l, f, l, b],
        [b, l, c, c, b, f],
        [s, s, c, c, b, b],
        [s, s, l, b, b, b],
        [s, s, b, f, f, l],
    ],
    arr1c1: [
        [f, b, b, f, c, c],
        [b, b, b, l, c, c],
        [b, l, b, b, l, b],
        [b, b, b, b, b, f],
        [b, s, s, s, l, f],
        [l, s, s, s, b, b],
    ],
    arr1c2: [
        [f, b, b, f, b, b],
        [b, b, b, l, b, b],
        [b, l, c, c, l, b],
        [b, b, c, c, b, f],
        [b, s, s, s, l, f],
        [l, s, s, s, b, b],
    ],
    arr2c1: [
        [b, b, b, b, c, c],
        [b, b, b, l, c, c],
        [b, l, b, b, l, b],
        [f, s, s, s, f, b],
        [f, s, s, s, l, b],
        [l, b, b, f, b, b],
    ],
    arr2c2: [
        [b, c, c, b, b, b],
        [b, c, c, l, b, b],
        [b, l, b, b, l, b],
        [f, s, s, s, f, b],
        [f, s, s, s, l, b],
        [l, b, b, f, b, b],
    ],
    arr3c1: [
        [b, b, b, b, c, c],
        [b, b, b, l, c, c],
        [b, l, f, b, l, b],
        [s, s, s, f, b, b],
        [s, s, s, f, l, b],
        [l, b, b, b, b, f],
    ],
    arr3c2: [
        [b, c, c, b, b, b],
        [b, c, c, l, b, b],
        [b, l, f, b, l, b],
        [s, s, s, f, b, b],
        [s, s, s, f, l, b],
        [l, b, b, b, b, f],
    ],
    arr4c1: [
        [f, c, c, f, b, b],
        [b, c, c, l, b, b],
        [b, l, b, b, l, b],
        [b, b, s, s, b, f],
        [b, b, s, s, l, f],
        [l, b, s, s, b, b],
    ],
    arr4c2: [
        [f, b, b, f, b, b],
        [b, b, b, l, b, b],
        [b, l, b, b, l, b],
        [c, c, s, s, b, f],
        [c, c, s, s, l, f],
        [l, b, s, s, b, b],
    ],
    arr5c1: [
        [b, b, b, b, c, c],
        [b, b, b, l, c, c],
        [b, l, f, b, l, b],
        [b, s, s, f, b, b],
        [b, s, s, f, l, b],
        [l, s, s, b, b, f],
    ],
    arr5c2: [
        [c, c, b, b, b, b],
        [c, c, b, l, b, b],
        [b, l, f, b, l, b],
        [b, s, s, f, b, b],
        [b, s, s, f, l, b],
        [l, s, s, b, b, f],
    ],
    arr6c1: [
        [b, b, b, b, c, c],
        [b, b, b, l, c, c],
        [f, l, s, s, l, f],
        [b, b, s, s, b, b],
        [b, b, s, s, l, b],
        [l, f, b, b, f, b],
    ],
    arr6c2: [
        [c, c, b, b, b, b],
        [c, c, b, l, b, b],
        [f, l, s, s, l, f],
        [b, b, s, s, b, b],
        [b, b, s, s, l, b],
        [l, f, b, b, f, b],
    ],
    arr7c1: [
        [s, s, s, b, b, b],
        [s, s, s, l, b, b],
        [f, l, b, b, l, f],
        [c, c, b, b, b, b],
        [c, c, b, b, l, b],
        [l, f, b, b, f, b],
    ],
    arr7c2: [
        [s, s, s, b, b, b],
        [s, s, s, l, b, b],
        [f, l, b, b, l, f],
        [b, b, b, b, b, b],
        [b, b, c, c, l, b],
        [l, f, c, c, f, b],
    ],
    arr7c3: [
        [s, s, s, b, b, b],
        [s, s, s, l, b, b],
        [b, l, b, b, l, b],
        [f, b, b, b, f, b],
        [f, c, c, b, l, b],
        [l, c, c, f, b, b],
    ],
    arr7c4: [
        [s, s, s, b, b, b],
        [s, s, s, l, b, b],
        [b, l, c, c, l, b],
        [f, b, c, c, f, b],
        [f, b, b, b, l, b],
        [l, b, b, f, b, b],
    ],
    adr1c1: [
        [l, b, b, b, b, f],
        [s, s, b, l, b, b],
        [s, s, b, b, b, b],
        [s, s, b, b, l, f],
        [b, l, b, l, c, c],
        [b, f, f, b, c, c],
    ],
    adr1c2: [
        [l, b, b, b, b, f],
        [s, s, b, l, b, b],
        [s, s, c, c, b, b],
        [s, s, c, c, l, f],
        [b, l, b, l, b, b],
        [b, f, f, b, b, b],
    ],
    adr2c1: [
        [l, f, f, b, b, b],
        [b, s, s, l, b, b],
        [b, s, s, b, b, b],
        [f, s, s, b, l, b],
        [b, l, f, l, c, c],
        [b, b, b, b, c, c],
    ],
    adr2c2: [
        [l, f, f, b, b, b],
        [b, s, s, l, c, c],
        [b, s, s, b, c, c],
        [f, s, s, b, l, b],
        [b, l, f, l, b, b],
        [b, b, b, b, b, b],
    ],
    adr3c1: [
        [l, s, s, b, b, b],
        [b, s, s, l, b, b],
        [b, s, s, f, b, b],
        [b, f, f, b, l, b],
        [b, l, b, l, c, c],
        [f, b, b, b, c, c],
    ],
    adr3c2: [
        [l, s, s, b, b, b],
        [b, s, s, l, c, c],
        [b, s, s, f, c, c],
        [b, f, f, b, l, b],
        [b, l, b, l, b, b],
        [f, b, b, b, b, b],
    ],
    adr4c1: [
        [l, b, b, b, b, f],
        [b, b, b, l, c, c],
        [s, s, s, b, c, c],
        [s, s, s, b, l, f],
        [b, l, b, l, b, b],
        [b, f, f, b, b, b]
    ],
    adr4c2: [
        [l, c, c, b, b, f],
        [b, c, c, l, b, b],
        [s, s, s, b, b, b],
        [s, s, s, b, l, f],
        [b, l, b, l, b, b],
        [b, f, f, b, b, b]
    ],
    adr5c1: [
        [l, b, b, b, b, b],
        [s, s, s, l, b, b],
        [s, s, s, f, b, b],
        [b, f, f, b, l, b],
        [b, l, b, l, c, c],
        [f, b, b, b, c, c],
    ],
    adr5c2: [
        [l, b, b, b, c, c],
        [s, s, s, l, c, c],
        [s, s, s, f, b, b],
        [b, f, f, b, l, b],
        [b, l, b, l, b, b],
        [f, b, b, b, b, b],
    ],
    adr6c1: [
        [l, b, b, f, b, b],
        [f, b, b, l, b, b],
        [b, s, s, s, b, b],
        [b, s, s, s, l, b],
        [f, l, b, l, c, c],
        [b, b, b, f, c, c],
    ],
    adr6c2: [
        [l, b, b, f, c, c],
        [f, b, b, l, c, c],
        [b, s, s, s, b, b],
        [b, s, s, s, l, b],
        [f, l, b, l, b, b],
        [b, b, b, f, b, b],
    ],
    adr7c1: [
        [l, c, c, f, s, s],
        [f, c, c, l, s, s],
        [b, b, b, b, s, s],
        [b, b, b, b, l, b],
        [f, l, b, l, b, b],
        [b, b, b, f, b, b],
    ],
    adr7c2: [
        [l, b, b, f, s, s],
        [f, b, b, l, s, s],
        [c, c, b, b, s, s],
        [c, c, b, b, l, b],
        [f, l, b, l, b, b],
        [b, b, b, f, b, b],
    ],
    ad4r7c3: [
        [l, f, f, b, s, s],
        [c, c, b, l, s, s],
        [c, c, b, b, s, s],
        [f, b, b, b, l, b],
        [b, l, f, l, b, b],
        [b, b, b, b, b, b],
    ],
    ad4r7c4: [
        [l, f, f, b, s, s],
        [b, b, b, l, s, s],
        [b, b, c, c, s, s],
        [f, b, c, c, l, b],
        [b, l, f, l, b, b],
        [b, b, b, b, b, b],
    ],
    alr1c1: [
        [b, b, s, s, s, l],
        [f, l, s, s, s, b],
        [f, b, b, b, b, b],
        [b, l, b, b, l, b],
        [c, c, l, b, b, b],
        [c, c, f, b, b, f],
    ],
    alr1c2: [
        [b, b, s, s, s, l],
        [f, l, s, s, s, b],
        [f, b, c, c, b, b],
        [b, l, c, c, l, b],
        [b, b, l, b, b, b],
        [b, b, f, b, b, f],
    ],
    alr2c1: [
        [b, b, f, b, b, l],
        [b, l, s, s, s, f],
        [b, f, s, s, s, f],
        [b, l, b, b, l, b],
        [c, c, l, b, b, b],
        [c, c, b, b, b, b],
    ],
    alr2c2: [
        [b, b, f, b, b, l],
        [b, l, s, s, s, f],
        [b, f, s, s, s, f],
        [b, l, b, b, l, b],
        [b, b, l, c, c, b],
        [b, b, b, c, c, b],
    ],
    alr3c1: [
        [f, b, b, b, b, l],
        [b, l, f, s, s, s],
        [b, b, f, s, s, s],
        [b, l, b, f, l, b],
        [c, c, l, b, b, b],
        [c, c, b, b, b, b],
    ],
    alr3c2: [
        [f, b, b, b, b, l],
        [b, l, f, s, s, s],
        [b, b, f, s, s, s],
        [b, l, b, f, l, b],
        [b, b, l, c, c, b],
        [b, b, b, c, c, b],
    ],
    alr4c1: [
        [b, b, s, s, b, l],
        [f, l, s, s, b, b],
        [f, b, s, s, b, b],
        [b, l, b, b, l, b],
        [b, b, l, c, c, b],
        [b, b, f, c, c, f],
    ],
    alr4c2: [
        [b, b, s, s, b, l],
        [f, l, s, s, c, c],
        [f, b, s, s, c, c],
        [b, l, b, b, l, b],
        [b, b, l, b, b, b],
        [b, b, f, b, b, f],
    ],
    alr5c1: [
        [f, b, b, s, s, l],
        [b, l, f, s, s, b],
        [b, b, f, s, s, b],
        [b, l, b, f, l, b],
        [c, c, l, b, b, b],
        [c, c, b, b, b, b],
    ],
    alr5c2: [
        [f, b, b, s, s, l],
        [b, l, f, s, s, b],
        [b, b, f, s, s, b],
        [b, l, b, f, l, b],
        [b, b, l, b, c, c],
        [b, b, b, b, c, c],
    ],
    alr6c1: [
        [b, f, b, b, f, l],
        [b, l, s, s, b, b],
        [b, b, s, s, b, b],
        [f, l, s, s, l, f],
        [c, c, l, b, b, b],
        [c, c, b, b, b, b],
    ],
    alr6c2: [
        [b, f, b, b, f, l],
        [b, l, s, s, b, b],
        [b, b, s, s, b, b],
        [f, l, s, s, l, f],
        [b, b, l, b, c, c],
        [b, b, b, b, c, c],
    ],
    alr7c1: [
        [b, f, b, b, f, l],
        [b, l, b, b, c, c],
        [b, b, b, b, c, c],
        [f, l, b, b, l, f],
        [b, b, l, s, s, s],
        [b, b, b, s, s, s],
    ],
    alr7c2: [
        [b, f, c, c, f, l],
        [b, l, c, c, b, b],
        [b, b, b, b, b, b],
        [f, l, b, b, l, f],
        [b, b, l, s, s, s],
        [b, b, b, s, s, s],
    ],
    alr7c3: [
        [b, b, f, c, c, l],
        [b, l, b, c, c, f],
        [b, f, b, b, b, f],
        [b, l, b, b, l, b],
        [b, b, l, s, s, s],
        [b, b, b, s, s, s],
    ],
    alr7c4: [
        [b, b, f, b, b, l],
        [b, l, b, b, b, f],
        [b, f, c, c, b, f],
        [b, l, c, c, l, b],
        [b, b, l, s, s, s],
        [b, b, b, s, s, s],
    ],
    bur1c1: [
        [s, s, s, l, c, c],
        [s, s, s, b, c, c],
        [b, l, b, f, l, b],
        [f, b, b, l, b, b],
        [b, b, f, b, b, b],
        [b, b, l, f, b, b],
    ],
    bur1c2: [
        [s, s, s, l, b, b],
        [s, s, s, b, b, b],
        [b, l, b, f, l, b],
        [f, b, b, l, b, b],
        [b, b, f, b, c, c],
        [b, b, l, f, c, c],
    ],
    bur1c3: [
        [s, s, s, l, b, b],
        [s, s, s, b, f, b],
        [b, l, f, b, l, b],
        [b, b, f, l, f, b],
        [c, c, b, b, b, b],
        [c, c, l, b, b, b],
    ],
    bur1c4: [
        [s, s, s, l, b, b],
        [s, s, s, b, f, b],
        [b, l, f, b, l, b],
        [b, b, f, l, f, b],
        [b, b, b, c, c, b],
        [b, b, l, c, c, b],
    ],
    bur2c1: [
        [b, b, b, l, b, b],
        [b, b, b, b, b, b],
        [b, l, b, f, l, b],
        [f, b, b, l, s, s],
        [c, c, f, b, s, s],
        [c, c, l, f, s, s],
    ],
    bur2c2: [
        [b, c, c, l, b, b],
        [b, c, c, b, b, b],
        [b, l, b, f, l, b],
        [f, b, b, l, s, s],
        [b, b, f, b, s, s],
        [b, b, l, f, s, s],
    ],
    bur2c3: [
        [b, f, b, l, b, b],
        [f, b, f, b, b, b],
        [b, l, b, b, l, f],
        [b, c, c, l, s, s],
        [b, c, c, b, s, s],
        [b, b, l, b, s, s],
    ],
    bur2c4: [
        [b, f, b, l, c, c],
        [f, b, f, b, c, c],
        [b, l, b, b, l, f],
        [b, b, b, l, s, s],
        [b, b, b, b, s, s],
        [b, b, l, b, s, s],
    ],
    bur3c1: [
        [b, f, b, l, c, c],
        [f, b, f, b, c, c],
        [b, l, b, b, l, f],
        [b, b, b, l, b, b],
        [b, b, b, s, s, s],
        [b, b, l, s, s, s],
    ],
    bur3c2: [
        [b, f, b, l, b, b],
        [f, b, f, b, b, b],
        [b, l, b, b, l, f],
        [b, b, b, l, b, b],
        [c, c, b, s, s, s],
        [c, c, l, s, s, s],
    ],
    bur4c1: [
        [c, c, b, l, b, b],
        [c, c, b, b, f, b],
        [b, l, f, b, l, b],
        [s, s, f, l, f, b],
        [s, s, b, b, b, b],
        [s, s, l, b, b, b],
    ],
    bur4c2: [
        [b, b, b, l, b, b],
        [b, b, b, b, f, b],
        [b, l, f, b, l, b],
        [s, s, f, l, f, b],
        [s, s, b, b, c, c],
        [s, s, l, b, c, c],
    ],
    bur4c3: [
        [b, b, f, l, b, f],
        [b, b, c, c, b, b],
        [f, l, c, c, l, b],
        [s, s, b, l, b, b],
        [s, s, b, b, b, b],
        [s, s, l, b, b, f],
    ],
    bur4c4: [
        [b, b, f, l, b, f],
        [b, b, b, b, b, b],
        [f, l, b, b, l, b],
        [s, s, b, l, c, c],
        [s, s, b, b, c, c],
        [s, s, l, b, b, f],
    ],
    bur5c1: [
        [c, c, f, l, b, f],
        [c, c, b, b, b, b],
        [f, l, b, b, l, b],
        [s, s, s, l, b, b],
        [s, s, s, b, b, b],
        [b, b, l, b, b, f],
    ],
    bur5c2: [
        [b, b, f, l, b, f],
        [b, b, b, b, b, b],
        [f, l, b, b, l, b],
        [s, s, s, l, b, b],
        [s, s, s, c, c, b],
        [b, b, l, c, c, f],
    ],
    brr1c1: [
        [b, b, f, b, s, s],
        [b, b, b, l, s, s],
        [l, f, b, b, s, s],
        [f, b, l, f, b, l],
        [b, b, b, l, c, c],
        [b, b, b, b, c, c],
    ],
    brr1c2: [
        [b, b, f, b, s, s],
        [b, b, b, l, s, s],
        [l, f, b, b, s, s],
        [f, b, l, f, b, l],
        [c, c, b, l, b, b],
        [c, c, b, b, b, b],
    ],
    brr1c3: [
        [c, c, b, b, s, s],
        [c, c, b, l, s, s],
        [l, b, f, f, s, s],
        [b, b, l, b, b, l],
        [b, b, f, l, f, b],
        [b, b, b, b, b, b],
    ],
    brr1c4: [
        [b, b, b, b, s, s],
        [b, b, b, l, s, s],
        [l, b, f, f, s, s],
        [c, c, l, b, b, l],
        [c, c, f, l, f, b],
        [b, b, b, b, b, b],
    ],
    brr2c1: [
        [c, c, f, b, b, b],
        [c, c, b, l, b, b],
        [l, f, b, b, b, b],
        [f, b, l, f, b, l],
        [s, s, s, l, b, b],
        [s, s, s, b, b, b],
    ],
    brr2c2: [
        [b, b, f, b, b, b],
        [b, b, b, l, c, c],
        [l, f, b, b, c, c],
        [f, b, l, f, b, l],
        [s, s, s, l, b, b],
        [s, s, s, b, b, b],
    ],
    brr2c3: [
        [b, b, b, b, f, b],
        [b, c, c, l, b, f],
        [l, c, c, b, f, b],
        [b, b, l, b, b, l],
        [s, s, s, l, b, b],
        [s, s, s, f, b, b],
    ],
    brr2c4: [
        [b, b, b, b, f, b],
        [b, b, b, l, b, f],
        [l, b, b, b, f, b],
        [b, b, l, b, b, l],
        [s, s, s, l, c, c],
        [s, s, s, f, c, c],
    ],
    brr3c1: [
        [b, b, b, b, f, b],
        [b, b, b, l, b, f],
        [l, b, b, b, f, b],
        [s, s, l, b, b, l],
        [s, s, b, l, c, c],
        [s, s, b, f, c, c],
    ],
    brr3c2: [
        [c, c, b, b, f, b],
        [c, c, b, l, b, f],
        [l, b, b, b, f, b],
        [s, s, l, b, b, l],
        [s, s, b, l, b, b],
        [s, s, b, f, b, b],
    ],
    brr4c1: [
        [s, s, s, b, c, c],
        [s, s, s, l, c, c],
        [l, b, f, f, b, b],
        [b, b, l, b, b, l],
        [b, b, f, l, f, b],
        [b, b, b, b, b, b],
    ],
    brr4c2: [
        [s, s, s, b, b, b],
        [s, s, s, l, b, b],
        [l, b, f, f, b, b],
        [b, b, l, b, b, l],
        [c, c, f, l, f, b],
        [c, c, b, b, b, b],
    ],
    brr4c3: [
        [s, s, s, f, b, b],
        [s, s, s, l, b, b],
        [l, b, b, c, c, f],
        [b, b, l, c, c, l],
        [b, b, b, l, b, b],
        [f, b, b, b, b, f],
    ],
    brr4c4: [
        [s, s, s, f, b, b],
        [s, s, s, l, b, b],
        [l, b, b, b, b, f],
        [b, b, l, b, b, l],
        [b, c, c, l, b, b],
        [f, c, c, b, b, f],
    ],
    brr5c1: [
        [b, s, s, f, c, c],
        [b, s, s, l, c, c],
        [l, s, s, b, b, f],
        [b, b, l, b, b, l],
        [b, b, b, l, b, b],
        [f, b, b, b, b, f],
    ],
    brr5c2: [
        [b, s, s, f, b, b],
        [b, s, s, l, b, b],
        [l, s, s, b, b, f],
        [c, c, l, b, b, l],
        [c, c, b, l, b, b],
        [f, b, b, b, b, f],
    ],
    bdr1c1: [
        [b, b, f, l, b, b],
        [b, b, b, f, b, b],
        [b, b, l, b, b, f],
        [b, l, f, b, l, b],
        [c, c, b, s, s, s],
        [c, c, l, s, s, s],
    ],
    bdr1c2: [
        [c, c, f, l, b, b],
        [c, c, b, f, b, b],
        [b, b, l, b, b, f],
        [b, l, f, b, l, b],
        [b, b, b, s, s, s],
        [b, b, l, s, s, s],
    ],
    bdr1c3: [
        [b, b, b, l, c, c],
        [b, b, b, b, c, c],
        [b, f, l, f, b, b],
        [b, l, b, f, l, b],
        [b, f, b, s, s, s],
        [b, b, l, s, s, s],
    ],
    bdr1c4: [
        [b, c, c, l, b, b],
        [b, c, c, b, b, b],
        [b, f, l, f, b, b],
        [b, l, b, f, l, b],
        [b, f, b, s, s, s],
        [b, b, l, s, s, s],
    ],
    bdr2c1: [
        [s, s, f, l, c, c],
        [s, s, b, f, c, c],
        [s, s, l, b, b, f],
        [b, l, f, b, l, b],
        [b, b, b, b, b, b],
        [b, b, l, b, b, b],
    ],
    bdr2c2: [
        [s, s, f, l, b, b],
        [s, s, b, f, b, b],
        [s, s, l, b, b, f],
        [b, l, f, b, l, b],
        [b, b, b, c, c, b],
        [b, b, l, c, c, b],
    ],
    bdr2c3: [
        [s, s, b, l, b, b],
        [s, s, b, c, c, b],
        [s, s, l, c, c, b],
        [f, l, b, b, l, b],
        [b, b, b, f, b, f],
        [b, b, l, b, f, b],
    ],
    bdr2c4: [
        [s, s, b, l, b, b],
        [s, s, b, b, b, b],
        [s, s, l, b, b, b],
        [f, l, b, b, l, b],
        [c, c, b, f, b, f],
        [c, c, l, b, f, b],
    ],
    bdr3c1: [
        [s, s, s, l, b, b],
        [s, s, s, b, b, b],
        [b, b, l, b, b, b],
        [f, l, b, b, l, b],
        [c, c, b, f, b, f],
        [c, c, l, b, f, b],
    ],
    bdr3c2: [
        [s, s, s, l, c, c],
        [s, s, s, b, c, c],
        [b, b, l, b, b, b],
        [f, l, b, b, l, b],
        [b, b, b, f, b, f],
        [b, b, l, b, f, b],
    ],
    bdr4c1: [
        [b, b, b, l, s, s],
        [b, b, b, b, s, s],
        [b, f, l, f, s, s],
        [b, l, b, f, l, b],
        [b, f, b, b, c, c],
        [b, b, l, b, c, c],
    ],
    bdr4c2: [
        [c, c, b, l, s, s],
        [c, c, b, b, s, s],
        [b, f, l, f, s, s],
        [b, l, b, f, l, b],
        [b, f, b, b, b, b],
        [b, b, l, b, b, b],
    ],
    bdr4c3: [
        [f, b, b, l, s, s],
        [b, b, b, b, s, s],
        [b, b, l, b, s, s],
        [b, l, c, c, l, f],
        [b, b, c, c, b, b],
        [f, b, l, f, b, b],
    ],
    bdr4c4: [
        [f, b, b, l, s, s],
        [c, c, b, b, s, s],
        [c, c, l, b, s, s],
        [b, l, b, b, l, f],
        [b, b, b, b, b, b],
        [f, b, l, f, b, b],
    ],
    bdr5c1: [
        [f, b, b, l, b, b],
        [b, b, b, s, s, s],
        [b, b, l, s, s, s],
        [b, l, b, b, l, f],
        [b, b, b, b, c, c],
        [f, b, l, f, c, c],
    ],
    bdr5c2: [
        [f, c, c, l, b, b],
        [b, c, c, s, s, s],
        [b, b, l, s, s, s],
        [b, l, b, b, l, f],
        [b, b, b, b, b, b],
        [f, b, l, f, b, b],
    ],
    blr1c1: [
        [c, c, b, b, b, b],
        [c, c, l, b, b, b],
        [l, b, f, l, b, f],
        [s, s, b, b, f, l],
        [s, s, l, b, b, b],
        [s, s, b, f, b, b],
    ],
    blr1c2: [
        [b, b, b, b, c, c],
        [b, b, l, b, c, c],
        [l, b, f, l, b, f],
        [s, s, b, b, f, l],
        [s, s, l, b, b, b],
        [s, s, b, f, b, b],
    ],
    blr1c3: [
        [b, b, b, b, b, b],
        [b, f, l, f, b, b],
        [l, b, b, l, b, b],
        [s, s, f, f, b, l],
        [s, s, l, b, c, c],
        [s, s, b, b, c, c],
    ],
    blr1c4: [
        [b, b, b, b, b, b],
        [b, f, l, f, c, c],
        [l, b, b, l, c, c],
        [s, s, f, f, b, l],
        [s, s, l, b, b, b],
        [s, s, b, b, b, b],
    ],
    blr2c1: [
        [b, b, b, s, s, s],
        [b, b, l, s, s, s],
        [l, b, f, l, b, f],
        [b, b, b, b, f, l],
        [b, b, l, b, c, c],
        [b, b, b, f, c, c],
    ],
    blr2c2: [
        [b, b, b, s, s, s],
        [b, b, l, s, s, s],
        [l, b, f, l, b, f],
        [c, c, b, b, f, l],
        [c, c, l, b, b, b],
        [b, b, b, f, b, b],
    ],
    blr2c3: [
        [b, b, f, s, s, s],
        [b, b, l, s, s, s],
        [l, b, b, l, b, b],
        [b, f, b, c, c, l],
        [f, b, l, c, c, b],
        [b, f, b, b, b, b],
    ],
    blr2c4: [
        [c, c, f, s, s, s],
        [c, c, l, s, s, s],
        [l, b, b, l, b, b],
        [b, f, b, b, b, l],
        [f, b, l, b, b, b],
        [b, f, b, b, b, b],
    ],
    blr3c1: [
        [c, c, f, b, s, s],
        [c, c, l, b, s, s],
        [l, b, b, l, s, s],
        [b, f, b, b, b, l],
        [f, b, l, b, b, b],
        [b, f, b, b, b, b],
    ],
    blr3c2: [
        [b, b, f, b, s, s],
        [b, b, l, b, s, s],
        [l, b, b, l, s, s],
        [b, f, b, b, b, l],
        [f, b, l, b, c, c],
        [b, f, b, b, c, c],
    ],
    blr4c1: [
        [b, b, b, b, b, b],
        [b, f, l, f, b, b],
        [l, b, b, l, b, b],
        [b, b, f, f, b, l],
        [c, c, l, s, s, s],
        [c, c, b, s, s, s],
    ],
    blr4c2: [
        [b, b, b, b, c, c],
        [b, f, l, f, c, c],
        [l, b, b, l, b, b],
        [b, b, f, f, b, l],
        [b, b, l, s, s, s],
        [b, b, b, s, s, s],
    ],
    blr4c3: [
        [f, b, b, b, b, f],
        [b, b, l, b, b, b],
        [l, c, c, l, b, b],
        [f, c, c, b, b, l],
        [b, b, l, s, s, s],
        [b, b, f, s, s, s],
    ],
    blr4c4: [
        [f, b, b, c, c, f],
        [b, b, l, c, c, b],
        [l, b, b, l, b, b],
        [f, b, b, b, b, l],
        [b, b, l, s, s, s],
        [b, b, f, s, s, s],
    ],
    blr5c1: [
        [f, b, b, b, b, f],
        [b, b, l, b, b, b],
        [l, b, b, l, b, b],
        [f, b, b, s, s, l],
        [c, c, l, s, s, b],
        [c, c, f, s, s, b],
    ],
    blr5c2: [
        [f, b, b, b, b, f],
        [b, b, l, b, c, c],
        [l, b, b, l, c, c],
        [f, b, b, s, s, l],
        [b, b, l, s, s, b],
        [b, b, f, s, s, b],
    ],
    cur1c1: [
        [f, b, b, b, l, b],
        [b, l, b, b, s, s],
        [c, c, b, l, s, s],
        [c, c, b, f, s, s],
        [b, l, b, f, b, b],
        [b, f, b, l, b, b],
    ],
    cur1c2: [
        [f, b, b, b, l, b],
        [b, l, b, b, s, s],
        [b, b, b, l, s, s],
        [b, b, b, f, s, s],
        [b, l, b, f, c, c],
        [b, f, b, l, c, c],
    ],
    cur2c1: [
        [b, b, b, b, l, b],
        [b, l, f, b, b, b],
        [c, c, b, l, s, s],
        [c, c, b, b, s, s],
        [f, l, b, b, s, s],
        [b, b, b, l, f, f],
    ],
    cur2c2: [
        [b, b, b, b, l, b],
        [b, l, f, b, b, b],
        [b, b, b, l, s, s],
        [b, b, c, c, s, s],
        [f, l, c, c, s, s],
        [b, b, b, l, f, f],
    ],
    cur3c1: [
        [b, b, c, c, l, b],
        [f, l, c, c, f, b],
        [b, b, b, l, b, f],
        [b, b, b, b, s, s],
        [b, l, f, b, s, s],
        [b, b, b, l, s, s],
    ],
    cur3c2: [
        [b, b, b, b, l, b],
        [f, l, b, b, f, b],
        [b, c, c, l, b, f],
        [b, c, c, b, s, s],
        [b, l, f, b, s, s],
        [b, b, b, l, s, s],
    ],
    cur3c3: [
        [b, f, b, b, l, f],
        [b, l, b, b, b, b],
        [b, b, f, l, b, b],
        [b, b, c, c, s, s],
        [b, l, c, c, s, s],
        [f, b, b, l, s, s],
    ],
    cur3c4: [
        [b, f, b, b, l, f],
        [b, l, b, b, b, b],
        [c, c, f, l, b, b],
        [c, c, b, b, s, s],
        [b, l, b, b, s, s],
        [f, b, b, l, s, s],
    ],
    cur4c1: [
        [b, b, c, c, l, b],
        [f, l, c, c, f, b],
        [b, b, b, l, b, f],
        [b, b, b, s, s, s],
        [b, l, f, s, s, s],
        [b, b, b, l, b, b],
    ],
    cur4c2: [
        [b, b, b, b, l, b],
        [f, l, b, b, f, b],
        [c, c, b, l, b, f],
        [c, c, b, s, s, s],
        [b, l, f, s, s, s],
        [b, b, b, l, b, b],
    ],
    cur4c3: [
        [b, b, b, b, l, b],
        [b, l, f, b, b, b],
        [b, c, c, l, b, b],
        [b, c, c, s, s, s],
        [f, l, b, s, s, s],
        [b, b, b, l, f, f],
    ],
    cur4c4: [
        [b, b, b, b, l, b],
        [b, l, f, b, c, c],
        [b, b, b, l, c, c],
        [b, b, b, s, s, s],
        [f, l, b, s, s, s],
        [b, b, b, l, f, f],
    ],
    cur5c1: [
        [b, f, c, c, l, f],
        [b, l, c, c, b, b],
        [b, b, f, l, b, b],
        [b, b, s, s, s, b],
        [b, l, s, s, s, b],
        [f, b, b, l, b, b],
    ],
    cur5c2: [
        [b, f, b, b, l, f],
        [b, l, b, b, c, c],
        [b, b, f, l, c, c],
        [b, b, s, s, s, b],
        [b, l, s, s, s, b],
        [f, b, b, l, b, b],
    ],
    cur6c1: [
        [f, b, c, c, l, b],
        [b, l, c, c, b, b],
        [s, s, s, l, b, b],
        [s, s, s, f, b, b],
        [b, l, b, f, b, b],
        [b, f, b, l, b, b],
    ],
    crr1c1: [
        [b, b, c, c, b, f],
        [f, l, c, c, l, b],
        [b, b, b, b, b, b],
        [l, f, f, l, b, b],
        [b, b, s, s, s, l],
        [b, b, s, s, s, b],
    ],
    crr1c2: [
        [b, b, b, b, b, f],
        [f, l, b, b, l, b],
        [b, b, b, b, b, b],
        [l, f, f, l, b, b],
        [c, c, s, s, s, l],
        [c, c, s, s, s, b],
    ],
    crr2c1: [
        [b, f, c, c, b, b],
        [b, l, c, c, l, b],
        [b, b, b, b, f, b],
        [l, b, b, l, b, b],
        [f, s, s, s, b, l],
        [f, s, s, s, b, b],
    ],
    crr2c2: [
        [b, f, b, b, b, b],
        [b, l, b, b, l, b],
        [b, c, c, b, f, b],
        [l, c, c, l, b, b],
        [f, s, s, s, b, l],
        [f, s, s, s, b, b],
    ],
    crr3c1: [
        [b, b, b, b, f, b],
        [b, l, b, b, l, b],
        [b, f, b, b, c, c],
        [l, b, b, l, c, c],
        [s, s, s, b, f, l],
        [s, s, s, f, b, b],
    ],
    crr3c2: [
        [b, b, b, b, f, b],
        [b, l, c, c, l, b],
        [b, f, c, c, b, b],
        [l, b, b, l, b, b],
        [s, s, s, b, f, l],
        [s, s, s, f, b, b],
    ],
    crr3c3: [
        [f, b, b, b, b, b],
        [b, l, b, b, l, f],
        [b, c, c, f, b, b],
        [l, c, c, l, b, b],
        [s, s, s, b, b, l],
        [s, s, s, b, b, f],
    ],
    crr3c4: [
        [f, b, c, c, b, b],
        [b, l, c, c, l, f],
        [b, b, b, f, b, b],
        [l, b, b, l, b, b],
        [s, s, s, b, b, l],
        [s, s, s, b, b, f],
    ],
    crr4c1: [
        [b, b, b, b, f, b],
        [b, l, b, b, l, b],
        [b, f, b, b, c, c],
        [l, s, s, l, c, c],
        [b, s, s, b, f, l],
        [b, s, s, f, b, b],
    ],
    crr4c2: [
        [b, b, c, c, f, b],
        [b, l, c, c, l, b],
        [b, f, b, b, b, b],
        [l, s, s, l, b, b],
        [b, s, s, b, f, l],
        [b, s, s, f, b, b],
    ],
    crr5c3: [
        [b, f, b, b, b, b],
        [b, l, c, c, l, b],
        [b, b, c, c, f, b],
        [l, s, s, l, b, b],
        [f, s, s, b, b, l],
        [f, s, s, b, b, b],
    ],
    crr5c4: [
        [b, f, b, b, b, b],
        [b, l, b, b, l, b],
        [b, b, b, b, f, b],
        [l, s, s, l, b, b],
        [f, s, s, c, c, l],
        [f, s, s, c, c, b],
    ],
    crr6c1: [
        [f, b, b, b, b, b],
        [b, l, b, b, l, f],
        [b, s, s, f, c, c],
        [l, s, s, l, c, c],
        [b, s, s, b, b, l],
        [b, b, b, b, b, f],
    ],
    crr6c2: [
        [f, b, b, b, b, b],
        [b, l, b, b, l, f],
        [b, s, s, f, b, b],
        [l, s, s, l, b, b],
        [b, s, s, c, c, l],
        [b, b, b, c, c, f],
    ],
    crr7c1: [
        [b, b, s, s, b, f],
        [f, l, s, s, l, b],
        [b, b, s, s, c, c],
        [l, f, f, l, c, c],
        [b, b, b, b, b, l],
        [b, b, b, b, b, b],
    ],
    cdr1c1: [
        [b, b, l, b, f, b],
        [b, b, f, b, l, b],
        [s, s, f, b, c, c],
        [s, s, l, b, c, c],
        [s, s, b, b, l, b],
        [b, l, b, b, b, f],
    ],
    cdr1c2: [
        [c, c, l, b, f, b],
        [c, c, f, b, l, b],
        [s, s, f, b, b, b],
        [s, s, l, b, b, b],
        [s, s, b, b, l, b],
        [b, l, b, b, b, f],
    ],
    cdr2c1: [
        [f, f, l, b, b, b],
        [s, s, b, b, l, f],
        [s, s, b, b, c, c],
        [s, s, l, b, c, c],
        [b, b, b, f, l, b],
        [b, l, b, b, b, b],
    ],
    cdr2c2: [
        [f, f, l, b, b, b],
        [s, s, c, c, l, f],
        [s, s, c, c, b, b],
        [s, s, l, b, b, b],
        [b, b, b, f, l, b],
        [b, l, b, b, b, b],
    ],
    cdr3c1: [
        [s, s, l, b, b, b],
        [s, s, b, f, l, b],
        [s, s, b, b, b, b],
        [f, b, l, b, b, b],
        [b, f, c, c, l, f],
        [b, l, c, c, b, b],
    ],
    cdr3c2: [
        [s, s, l, b, b, b],
        [s, s, b, f, l, b],
        [s, s, b, c, c, b],
        [f, b, l, c, c, b],
        [b, f, b, b, l, f],
        [b, l, b, b, b, b],
    ],
    cdr3c3: [
        [s, s, l, b, b, f],
        [s, s, c, c, l, b],
        [s, s, c, c, b, b],
        [b, b, l, f, b, b],
        [b, b, b, b, l, b],
        [f, l, b, b, f, b],
    ],
    cdr3c4: [
        [s, s, l, b, b, f],
        [s, s, b, b, l, b],
        [s, s, b, b, c, c],
        [b, b, l, f, c, c],
        [b, b, b, b, l, b],
        [f, l, b, b, f, b],
    ],
    cdr4c1: [
        [b, b, l, b, b, b],
        [s, s, s, f, l, b],
        [s, s, s, b, b, b],
        [f, b, l, b, b, b],
        [b, f, c, c, l, f],
        [b, l, c, c, b, b],
    ],
    cdr4c2: [
        [b, b, l, b, b, b],
        [s, s, s, f, l, b],
        [s, s, s, b, c, c],
        [f, b, l, b, c, c],
        [b, f, b, b, l, f],
        [b, l, b, b, b, b],
    ],
    cdr4c3: [
        [f, f, l, b, b, b],
        [s, s, s, b, l, f],
        [s, s, s, c, c, b],
        [b, b, l, c, c, b],
        [b, b, b, f, l, b],
        [b, l, b, b, b, b],
    ],
    cdr4c4: [
        [f, f, l, b, b, b],
        [s, s, s, b, l, f],
        [s, s, s, b, b, b],
        [c, c, l, b, b, b],
        [c, c, b, f, l, b],
        [b, l, b, b, b, b],
    ],
    cdr5c1: [
        [b, b, l, b, b, f],
        [b, s, s, s, l, b],
        [b, s, s, s, b, b],
        [b, b, l, f, b, b],
        [b, b, c, c, l, b],
        [f, l, c, c, f, b],
    ],
    cdr5c2: [
        [b, b, l, b, b, f],
        [b, s, s, s, l, b],
        [b, s, s, s, b, b],
        [c, c, l, f, b, b],
        [c, c, b, b, l, b],
        [f, l, b, b, f, b],
    ],
    cdr6c1: [
        [b, b, l, b, f, b],
        [b, b, f, b, l, b],
        [b, b, f, s, s, s],
        [b, b, l, s, s, s],
        [b, b, c, c, l, b],
        [b, l, c, c, b, f],
    ],
    clr1c1: [
        [b, s, s, s, b, b],
        [l, s, s, s, b, b],
        [b, b, l, f, f, l],
        [b, b, b, b, b, b],
        [b, l, c, c, l, f],
        [f, b, c, c, b, b],
    ],
    clr1c2: [
        [b, s, s, s, c, c],
        [l, s, s, s, c, c],
        [b, b, l, f, f, l],
        [b, b, b, b, b, b],
        [b, l, b, b, l, f],
        [f, b, b, b, b, b],
    ],
    clr2c1: [
        [b, b, s, s, s, f],
        [l, b, s, s, s, f],
        [b, b, l, b, b, l],
        [b, f, b, b, b, b],
        [b, l, c, c, l, b],
        [b, b, c, c, f, b],
    ],
    clr2c2: [
        [b, b, s, s, s, f],
        [l, b, s, s, s, f],
        [b, b, l, c, c, l],
        [b, f, b, c, c, b],
        [b, l, b, b, l, b],
        [b, b, b, b, f, b],
    ],
    clr3c1: [
        [b, b, f, s, s, s],
        [l, f, b, s, s, s],
        [c, c, l, b, b, l],
        [c, c, b, b, f, b],
        [b, l, b, b, l, b],
        [b, f, b, b, b, b],
    ],
    clr3c2: [
        [b, b, f, s, s, s],
        [l, f, b, s, s, s],
        [b, b, l, b, b, l],
        [b, b, c, c, f, b],
        [b, l, c, c, l, b],
        [b, f, b, b, b, b],
    ],
    clr3c3: [
        [f, b, b, s, s, s],
        [l, b, b, s, s, s],
        [b, b, l, c, c, l],
        [b, b, f, c, c, b],
        [f, l, b, b, l, b],
        [b, b, b, b, b, f],
    ],
    clr3c4: [
        [f, b, b, s, s, s],
        [l, b, b, s, s, s],
        [b, b, l, b, b, l],
        [b, b, f, b, b, b],
        [f, l, c, c, l, b],
        [b, b, c, c, b, f],
    ],
    clr4c1: [
        [b, b, f, s, s, b],
        [l, f, b, s, s, b],
        [c, c, l, s, s, l],
        [c, c, b, b, f, b],
        [b, l, b, b, l, b],
        [b, f, b, b, b, b],
    ],
    clr4c2: [
        [b, b, f, s, s, b],
        [l, f, b, s, s, b],
        [b, b, l, s, s, l],
        [b, b, b, b, f, b],
        [b, l, c, c, l, b],
        [b, f, c, c, b, b],
    ],
    clr4c3: [
        [b, b, b, s, s, f],
        [l, b, b, s, s, f],
        [b, b, l, s, s, l],
        [b, f, c, c, b, b],
        [b, l, c, c, l, b],
        [b, b, b, b, f, b],
    ],
    clr4c4: [
        [b, c, c, s, s, f],
        [l, c, c, s, s, f],
        [b, b, l, s, s, l],
        [b, f, b, b, b, b],
        [b, l, b, b, l, b],
        [b, b, b, b, f, b],
    ],
    clr5c1: [
        [f, b, b, b, b, b],
        [l, b, b, s, s, b],
        [c, c, l, s, s, l],
        [c, c, f, s, s, b],
        [f, l, b, b, l, b],
        [b, b, b, b, b, f],
    ],
    clr5c2: [
        [f, c, c, b, b, b],
        [l, c, c, s, s, b],
        [b, b, l, s, s, l],
        [b, b, f, s, s, b],
        [f, l, b, b, l, b],
        [b, b, b, b, b, f],
    ],
    clr6c1: [
        [b, b, b, b, b, b],
        [l, b, b, b, b, b],
        [c, c, l, f, f, l],
        [c, c, s, s, b, b],
        [b, l, s, s, l, f],
        [f, b, s, s, b, b],
    ],
    dur1c1: [
        [b, b, s, s, s, b],
        [b, l, s, s, s, f],
        [b, b, c, c, l, b],
        [l, b, c, c, b, b],
        [f, b, b, l, b, b],
        [b, f, l, b, f, b],
    ],
    dur1c2: [
        [b, b, s, s, s, b],
        [b, l, s, s, s, f],
        [b, b, b, b, l, b],
        [l, c, c, b, b, b],
        [f, c, c, l, b, b],
        [b, f, l, b, f, b],
    ],
    dur2c1: [
        [f, b, b, s, s, s],
        [b, l, b, s, s, s],
        [b, b, b, f, l, b],
        [l, b, b, f, c, c],
        [b, b, b, l, c, c],
        [b, b, l, b, b, f],
    ],
    dur2c2: [
        [f, b, b, s, s, s],
        [b, l, b, s, s, s],
        [b, b, b, f, l, b],
        [l, b, b, f, b, b],
        [c, c, b, l, b, b],
        [c, c, l, b, b, f],
    ],
    dur3c1: [
        [b, f, s, s, c, c],
        [b, l, s, s, c, c],
        [b, f, s, s, l, f],
        [l, b, b, b, b, b],
        [b, b, f, l, b, b],
        [b, b, l, b, b, b],
    ],
    dur3c2: [
        [b, f, s, s, b, b],
        [b, l, s, s, b, b],
        [b, f, s, s, l, f],
        [l, b, b, b, b, b],
        [c, c, f, l, b, b],
        [c, c, l, b, b, b],
    ],
    dur4c1: [
        [b, b, f, f, b, b],
        [b, l, s, s, b, b],
        [b, b, s, s, l, b],
        [l, b, s, s, b, f],
        [b, b, b, l, c, c],
        [b, b, l, f, c, c],
    ],
    dur4c2: [
        [b, b, f, f, b, b],
        [b, l, s, s, b, b],
        [b, b, s, s, l, b],
        [l, b, s, s, b, f],
        [c, c, b, l, b, b],
        [c, c, l, f, b, b],
    ],
    dur5c1: [
        [b, f, c, c, b, b],
        [b, l, c, c, b, b],
        [b, f, b, b, l, f],
        [l, b, b, b, s, s],
        [b, b, f, l, s, s],
        [b, b, l, b, s, s],
    ],
    dur5c2: [
        [b, f, b, b, c, c],
        [b, l, b, b, c, c],
        [b, f, b, b, l, f],
        [l, b, b, b, s, s],
        [b, b, f, l, s, s],
        [b, b, l, b, s, s],
    ],
    dur6c1: [
        [f, b, c, c, b, b],
        [b, l, c, c, b, b],
        [b, s, s, f, l, b],
        [l, s, s, f, b, b],
        [b, s, s, l, b, b],
        [b, b, l, b, b, f],
    ],
    dur6c2: [
        [f, b, b, b, b, b],
        [b, l, b, b, b, b],
        [b, s, s, f, l, b],
        [l, s, s, f, c, c],
        [b, s, s, l, c, c],
        [b, b, l, b, b, f],
    ],
    dur7c1: [
        [b, b, c, c, b, b],
        [b, l, c, c, b, f],
        [b, s, s, s, l, b],
        [l, s, s, s, b, b],
        [f, b, b, l, b, b],
        [b, f, l, b, f, b],
    ],
    dur7c2: [
        [b, b, b, b, b, b],
        [b, l, b, b, b, f],
        [b, s, s, s, l, b],
        [l, s, s, s, c, c],
        [f, b, b, l, c, c],
        [b, f, l, b, f, b],
    ],
    dur7c3: [
        [b, b, f, f, c, c],
        [b, l, b, b, c, c],
        [b, s, s, s, l, b],
        [l, s, s, s, b, f],
        [b, b, b, l, b, b],
        [b, b, l, f, b, b],
    ],
    dur7c4: [
        [b, b, f, f, b, b],
        [b, l, b, b, b, b],
        [b, s, s, s, l, b],
        [l, s, s, s, b, f],
        [b, b, b, l, c, c],
        [b, b, l, f, c, c],
    ],
    drr1c1: [
        [b, f, l, b, b, b],
        [f, b, b, b, l, b],
        [l, b, c, c, s, s],
        [b, l, c, c, s, s],
        [f, b, b, l, s, s],
        [b, b, b, b, f, b],
    ],
    drr1c2: [
        [b, f, l, b, b, b],
        [f, c, c, b, l, b],
        [l, c, c, b, s, s],
        [b, l, b, b, s, s],
        [f, b, b, l, s, s],
        [b, b, b, b, f, b],
    ],
    drr2c1: [
        [b, b, l, b, b, f],
        [b, b, b, b, l, b],
        [l, b, b, b, b, b],
        [b, l, f, f, s, s],
        [b, c, c, l, s, s],
        [f, c, c, b, s, s],
    ],
    drr2c2: [
        [c, c, l, b, b, f],
        [c, c, b, b, l, b],
        [l, b, b, b, b, b],
        [b, l, f, f, s, s],
        [b, b, b, l, s, s],
        [f, b, b, b, s, s],
    ],
    drr3c1: [
        [b, b, l, b, b, b],
        [b, b, b, f, l, f],
        [l, f, b, s, s, s],
        [b, l, b, s, s, s],
        [b, b, b, l, c, c],
        [b, b, b, f, c, c],
    ],
    drr3c2: [
        [c, c, l, b, b, b],
        [c, c, b, f, l, f],
        [l, f, b, s, s, s],
        [b, l, b, s, s, s],
        [b, b, b, l, b, b],
        [b, b, b, f, b, b],
    ],
    drr4c1: [
        [b, b, l, b, b, b],
        [b, b, b, b, l, b],
        [l, b, s, s, s, f],
        [f, l, s, s, s, f],
        [c, c, b, l, b, b],
        [c, c, f, b, b, b],
    ],
    drr4c2: [
        [c, c, l, b, b, b],
        [c, c, b, b, l, b],
        [l, b, s, s, s, f],
        [f, l, s, s, s, f],
        [b, b, b, l, b, b],
        [b, b, f, b, b, b],
    ],
    drr5c1: [
        [b, b, l, b, b, b],
        [b, b, b, f, l, f],
        [l, f, b, b, c, c],
        [b, l, b, b, c, c],
        [s, s, s, l, b, b],
        [s, s, s, f, b, b],
    ],
    drr5c2: [
        [b, b, l, b, b, b],
        [b, b, b, f, l, f],
        [l, f, b, b, b, b],
        [b, l, b, b, b, b],
        [s, s, s, l, c, c],
        [s, s, s, f, c, c],
    ],
    drr6c1: [
        [b, b, l, b, b, f],
        [b, s, s, s, l, b],
        [l, s, s, s, c, c],
        [b, l, f, f, c, c],
        [b, b, b, l, b, b],
        [f, b, b, b, b, b],
    ],
    drr6c2: [
        [b, b, l, b, b, f],
        [b, s, s, s, l, b],
        [l, s, s, s, b, b],
        [b, l, f, f, b, b],
        [b, c, c, l, b, b],
        [f, c, c, b, b, b],
    ],
    drr7c1: [
        [b, f, l, b, b, b],
        [f, b, s, s, l, b],
        [l, b, s, s, c, c],
        [b, l, s, s, c, c],
        [f, b, b, l, b, b],
        [b, b, b, b, f, b],
    ],
    drr7c2: [
        [b, f, l, b, b, b],
        [f, b, s, s, l, b],
        [l, b, s, s, b, b],
        [b, l, s, s, b, b],
        [f, c, c, l, b, b],
        [b, c, c, b, f, b],
    ],
    drr7c3: [
        [b, b, l, b, b, b],
        [b, b, s, s, l, b],
        [l, b, s, s, b, f],
        [f, l, s, s, b, f],
        [b, b, b, l, c, c],
        [b, b, f, b, c, c],
    ],
    drr7c4: [
        [b, b, l, b, b, b],
        [b, b, s, s, l, b],
        [l, b, s, s, b, f],
        [f, l, s, s, b, f],
        [c, c, b, l, b, b],
        [c, c, f, b, b, b],
    ],
    ddr1c1: [
        [b, f, b, l, f, b],
        [b, b, l, b, b, f],
        [b, b, c, c, b, l],
        [b, l, c, c, b, b],
        [f, s, s, s, l, b],
        [b, s, s, s, b, b],
    ],
    ddr1c2: [
        [b, f, b, l, f, b],
        [b, b, l, c, c, f],
        [b, b, b, c, c, l],
        [b, l, b, b, b, b],
        [f, s, s, s, l, b],
        [b, s, s, s, b, b],
    ],
    ddr2c1: [
        [f, b, b, l, b, b],
        [c, c, l, b, b, b],
        [c, c, f, b, b, l],
        [b, l, f, b, b, b],
        [s, s, s, b, l, b],
        [s, s, s, b, b, f],
    ],
    ddr2c2: [
        [f, b, b, l, c, c],
        [b, b, l, b, c, c],
        [b, b, f, b, b, l],
        [b, l, f, b, b, b],
        [s, s, s, b, l, b],
        [s, s, s, b, b, f],
    ],
    ddr3c1: [
        [b, b, b, l, b, b],
        [b, b, l, f, b, b],
        [b, b, b, b, b, l],
        [f, l, s, s, f, b],
        [c, c, s, s, l, b],
        [c, c, s, s, f, b],
    ],
    ddr3c2: [
        [b, b, b, l, c, c],
        [b, b, l, f, c, c],
        [b, b, b, b, b, l],
        [f, l, s, s, f, b],
        [b, b, s, s, l, b],
        [b, b, s, s, f, b],
    ],
    ddr4c1: [
        [c, c, f, l, b, b],
        [c, c, l, b, b, b],
        [f, b, s, s, b, l],
        [b, l, s, s, b, b],
        [b, b, s, s, l, b],
        [b, b, f, f, b, b],
    ],
    ddr4c2: [
        [b, b, f, l, c, c],
        [b, b, l, b, c, c],
        [f, b, s, s, b, l],
        [b, l, s, s, b, b],
        [b, b, s, s, l, b],
        [b, b, f, f, b, b],
    ],
    ddr5c1: [
        [s, s, b, l, b, b],
        [s, s, l, f, b, b],
        [s, s, b, b, b, l],
        [f, l, b, b, f, b],
        [b, b, c, c, l, b],
        [b, b, c, c, f, b],
    ],
    ddr5c2: [
        [s, s, b, l, b, b],
        [s, s, l, f, b, b],
        [s, s, b, b, b, l],
        [f, l, b, b, f, b],
        [c, c, b, b, l, b],
        [c, c, b, b, f, b],
    ],
    ddr6c1: [
        [f, b, b, l, b, b],
        [b, b, l, s, s, b],
        [b, b, f, s, s, l],
        [b, l, f, s, s, b],
        [b, b, c, c, l, b],
        [b, b, c, c, b, f],
    ],
    ddr6c2: [
        [f, b, b, l, b, b],
        [c, c, l, s, s, b],
        [c, c, f, s, s, l],
        [b, l, f, s, s, b],
        [b, b, b, b, l, b],
        [b, b, b, b, b, f],
    ],
    ddr7c1: [
        [b, f, b, l, f, b],
        [b, b, l, b, b, f],
        [b, b, s, s, s, l],
        [b, l, s, s, s, b],
        [f, b, c, c, l, b],
        [b, b, c, c, b, b],
    ],
    ddr7c2: [
        [b, f, b, l, f, b],
        [c, c, l, b, b, f],
        [c, c, s, s, s, l],
        [b, l, s, s, s, b],
        [f, b, b, b, l, b],
        [b, b, b, b, b, b],
    ],
    ddr7c3: [
        [b, b, f, l, b, b],
        [b, b, l, b, b, b],
        [f, b, s, s, s, l],
        [b, l, s, s, s, b],
        [c, c, b, b, l, b],
        [c, c, f, f, b, b], 
    ],
    ddr7c4: [
        [c, c, f, l, b, b],
        [c, c, l, b, b, b],
        [f, b, s, s, s, l],
        [b, l, s, s, s, b],
        [b, b, b, b, l, b],
        [b, b, f, f, b, b], 
    ],
    dlr1c1: [
        [b, f, b, b, b, b],
        [s, s, l, b, b, f],
        [s, s, c, c, l, b],
        [s, s, c, c, b, l],
        [b, l, b, b, b, f],
        [b, b, b, l, f, b],
    ],
    dlr1c2: [
        [b, f, b, b, b, b],
        [s, s, l, b, b, f],
        [s, s, b, b, l, b],
        [s, s, b, c, c, l],
        [b, l, b, c, c, f],
        [b, b, b, l, f, b],
    ],
    dlr2c1: [
        [s, s, b, c, c, f],
        [s, s, l, c, c, b],
        [s, s, f, f, l, b],
        [b, b, b, b, b, l],
        [b, l, b, b, b, b],
        [f, b, b, l, b, b],
    ],
    dlr2c2: [
        [s, s, b, b, b, f],
        [s, s, l, b, b, b],
        [s, s, f, f, l, b],
        [b, b, b, b, b, l],
        [b, l, b, b, c, c],
        [f, b, b, l, c, c],
    ],
    dlr3c1: [
        [c, c, f, b, b, b],
        [c, c, l, b, b, b],
        [s, s, s, b, l, b],
        [s, s, s, b, f, l],
        [f, l, f, b, b, b],
        [b, b, b, l, b, b],
    ],
    dlr3c2: [
        [b, b, f, b, b, b],
        [b, b, l, b, b, b],
        [s, s, s, b, l, b],
        [s, s, s, b, f, l],
        [f, l, f, b, c, c],
        [b, b, b, l, c, c],
    ],
    dlr4c1: [
        [b, b, b, f, c, c],
        [b, b, l, b, c, c],
        [f, s, s, s, l, f],
        [f, s, s, s, b, l],
        [b, l, b, b, b, b],
        [b, b, b, l, b, b],
    ],
    dlr4c2: [
        [b, b, b, f, b, b],
        [b, b, l, b, b, b],
        [f, s, s, s, l, f],
        [f, s, s, s, b, l],
        [b, l, b, b, c, c],
        [b, b, b, l, c, c],
    ],
    dlr5c1: [
        [b, b, f, s, s, s],
        [b, b, l, s, s, s],
        [c, c, b, b, l, b],
        [c, c, b, b, f, l],
        [f, l, f, b, b, b],
        [b, b, b, l, b, b],
    ],
    dlr5c2: [
        [c, c, f, s, s, s],
        [c, c, l, s, s, s],
        [b, b, b, b, l, b],
        [b, b, b, b, f, l],
        [f, l, f, b, b, b],
        [b, b, b, l, b, b],
    ],
    dlr6c1: [
        [b, b, b, b, b, f],
        [b, b, l, b, b, b],
        [c, c, f, f, l, b],
        [c, c, s, s, s, l],
        [b, l, s, s, s, b],
        [f, b, b, l, b, b],
    ],
    dlr6c2: [
        [b, b, b, c, c, f],
        [b, b, l, c, c, b],
        [b, b, f, f, l, b],
        [b, b, s, s, s, l],
        [b, l, s, s, s, b],
        [f, b, b, l, b, b],
    ],
    dlr7c1: [
        [b, f, b, b, b, b],
        [b, b, l, b, b, f],
        [c, c, s, s, l, b],
        [c, c, s, s, b, l],
        [b, l, s, s, b, f],
        [b, b, b, l, f, b],
    ],
    dlr7c2: [
        [b, f, b, c, c, b],
        [b, b, l, c, c, f],
        [b, b, s, s, l, b],
        [b, b, s, s, b, l],
        [b, l, s, s, b, f],
        [b, b, b, l, f, b],
    ],
    dlr7c3: [
        [c, c, b, f, b, b],
        [c, c, l, b, b, b],
        [f, b, s, s, l, f],
        [f, b, s, s, b, l],
        [b, l, s, s, b, b],
        [b, b, b, l, b, b],
    ],
    dlr7c4: [
        [b, b, b, f, c, c],
        [b, b, l, b, c, c],
        [f, b, s, s, l, f],
        [f, b, s, s, b, l],
        [b, l, s, s, b, b],
        [b, b, b, l, b, b],
    ],
}